### ISSUE TITLE
Which IRC channel?

### ISSUE THREAD

**Issue by Valiec** [deltamc-project/Support#1]
The short description on the main deltamc-project page says #deltamc, but the readme says #CMAN.

**Comment by williambl** [comment]
Perhaps we could move to discord anyway, seeing as more people tend to use it nowadays and it is a little more user-friendly. Shall I make a server?

**Comment by Valiec** [comment]
Definitely. I like Discord too (I was thinking of this already actually). If you have any questions about setting up the server (especially about making the roles behave properly), just ask me (I've set up multiple Discord servers before).

**Comment by williambl** [comment]
I'll send you a PM on curseforge with an invite link so I can make you an admin :D

**Comment by williambl** [comment]
@randomtestfive I've sent you a curseforge PM too but seeing as you haven't been online on it for a few months I thought I'd send you a message here too, just in case you're interested.

**Comment by Valiec** [comment]
Discord server created, so I'm closing this issue now (no longer relevant).
